import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import process from 'node:process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/objest/objest (repository URL provisional)
*/`;

const embeddedAssetPlugin = {
	name: 'embedded-ocr-assets',
	setup(build) {
		build.onLoad(
			{
				filter: /(pdf\.worker\.min\.mjs|tesseract\.js\/dist\/worker\.min\.js|tesseract-core-lstm\.wasm\.js)$/,
			},
			async (args) => ({
				contents: await import('node:fs/promises').then((fs) =>
					fs.readFile(args.path, 'utf8'),
				),
				loader: 'text',
			}),
		);
		build.onLoad({ filter: /eng\.traineddata\.gz$/ }, async (args) => ({
			contents: await import('node:fs/promises').then((fs) =>
				fs.readFile(args.path),
			),
			loader: 'binary',
		}));
	},
};

const production = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: { js: banner },
	bundle: true,
	entryPoints: ['src/main.ts'],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	logLevel: 'info',
	minify: production,
	outfile: 'main.js',
	platform: 'browser',
	plugins: [embeddedAssetPlugin],
	sourcemap: production ? false : 'inline',
	target: 'es2022',
	treeShaking: true,
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
